spring:
  application:
    name: backend

  datasource:
    url: jdbc:postgresql://localhost:5432/projectmanager_db
    username: admin
    password: 1234

  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.xml

  jpa:
    hibernate:
      ddl-auto: validate